### ISSUE TITLE
検索時にキャプションを対象に加える・検索対象を限定する機能

### ISSUE THREAD

**Issue by mikageymir** [aipictors/feedback#26]
検索対象に、キャプションを加える。

また、検索対象を絞れるようにする
・タグ
・タイトル
・キャプション
・プロンプト

現在は1件もヒットしないとすべての作品が表示されるので、対象が見つからなかったメッセージを表示するように修正する。

ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969294357692487/1094731825898868756

**Comment by mikageymir** [comment]
サイト上部の検索について、気になるところです。
（ほかチケットの報告もまとめてます）
・チケット
　・検索時にキャプションを対象に加える・検索対象を限定する機能
　　https://github.com/nakatsuka-k/AIPictors/issues/26
　・検索結果画面で0件の条件にするとその後の表示が崩れる
　　https://github.com/nakatsuka-k/AIPictors/issues/17
　・検索画面の表示不具合
　　https://github.com/nakatsuka-k/AIPictors/issues/16
・右側の検索ボタンを押すと、小さい検索窓が開く形となっています。
　検索結果一覧にいくには、文字を入れてEnterを押す必要があり、スマホでは推移できません。
　このため結果の閲覧がかなりし辛い状況になってしまっていると思います。
・小さい検索窓と、Enter押して遷移した検索結果画面では、設定できる内容が異なります。
・小さい検索窓の方で作品をクリックすると、1作品だけのダイアログ表示となります。
　検索結果画面の方では前後への移動が可能です。
・サイトトップから画面上部の検索に文字を入れて検索すると、小さい検索窓で
　作品クリックで作品ダイアログが開きます。
　しかし、検索結果画面に行った後、その画面で上部の検索ボックスに文字を入れて検索窓を出すと、
　作品クリックでも作品ダイアログが表示されません。
　同様に、マイページ、ダッシュボード画面からなども見れません。一覧系の画面ではない場合に
　何らか処理に失敗しているようです。
・R18モードで検索しても、検索結果からはR18が除外されます。
　サイト上部なので独立しているとは思いますが、一覧画面から使う場合は、
　その時の表示設定（通常／R18の切り替えと、性的描写非表示）が反映されたほうが良いと思います。
・フィルタ用のcheckboxの動作が、すべてオフであればフィルタなし扱いとなっているので、
　わかりにくいように思います。
　プロンプトなし・プロンプトあり、にして、デフォルトフィルタがないものはすべてcheckが
　入った状態（通知のフィルタと同じような動き）にするのが良いと思います。
・古い順、いいね順、閲覧順をすべて同時にONにできてしまいます。
　[新しい順][古い順][いいね順][閲覧数順]、のradioボタンにするのが良さそうです。
・検索結果は、他と異なりスクロールしても自動で続きが表示されず、画面下のもっと見るボタンを押す必要がある。
　もっと見るボタンはスクロールするとサイトのフッターの上に重なってしまうため、
　スクロール後に続きを見ようとしたとき、ボタンを認識しにくい。

以上をふまえて、以下のような検索機能にするのはどうでしょうか。

・検索時の入力途中のプレビューは表示しないことにし、文字入力後検索アイコンクリックで
　検索結果画面に遷移するようにする。
・検索結果画面の設定は、デフォルトで折りたたんで表示し、検索結果の表示に広い面積を使うようにする。
・検索設定の折りたたみを広げると以下のようなUI
　・種別：[全年齢✓][全年齢(性的描写あり)✓][R-18][R-18G]
　　※一覧画面の場合は、その時点での表示設定を反映する
　・検索対象：[タグ✓][タイトル✓][キャプション✓][プロンプト✓][作成者名✓]
　　※作成者名での検索も統合してしまいます。意図しないヒットがあるかもしれませんが、現状
　　　作成者名で調べるのがなかなかやりづらいと思いますので…。
　・使用AI：[すべて|▼]
　・使用モデル：[        ]
　・プロンプト：[プロンプトなし✓][プロンプトあり✓]
　・フォロー：[フォロー外✓][フォロー中✓]
　・テイスト：[リアル系✓][セミリアル系✓][イラスト系✓]
　・並べ替え：[新しい順✓][古い順][いいね順][閲覧数順]
　　※他のボタンを押すとトグル動作となり１つだけが✓できる
　・検索件数：[100件✓][200件][500件][1000件]
　　※他のボタンを押すとトグル動作となり１つだけが✓できる
　・□作品詳細表示
・折りたたみの下にキーワードの入力UI
　・[（キーワード入力TEXTBOX）]  [ 検索する ]
　　※画面上部で入れたものを初期表示
・検索の場合、続きを表示をするときに、前回の操作との間に検索結果に該当する投稿がされた場合、
　きれいに処理するのはなかなか難しいと思います。
　そのため、検索結果の件数を選べるようにし、続きの表示はなしにしてはいかがでしょうか。
　（最大で1000件としたのでそれを超える検索はできないですが、1000件見るケースはほぼないと
　　思いますので。。。）

**Comment by haruharu-1105** [comment]
検索機能に追加するのは賛成です。

機能としてほしいのは
・検索履歴
・検索クエリをブラウザのブックマークに登録したい。
　(理想はPixivのお気に入りタグ)
　理由：タグでウォッチしたいため

**Comment by haruharu-1105** [comment]
ちゃぶ台をひっくり返すようで申し訳ないのですが、個人的に気になった点です。
とりとめなく書いているので、別IssueかDiscussionsのほうが良いですかね？

1. 検索画面のUIについて
 検索機能はtwitterやPinterestの画面が、
 慣れていて個人的に使いやすく好みなのですが、
 他の方はどう感じているのか気になりました。
 （このまま追加していくとどんどん検索項目が多くなる気がしていてそれも懸念をしていたりも）

1. 検索機能を使われる方のペルソナ(ユーザー像)が気になりました。
ご存知だったら申し訳ないのですが、
SNSが使われる時間帯の一般論として4パターンあります。

- 朝の通勤・通学中
- 昼休み(12:00～13:00)
- 平日の夕方(18:00～19:00)
- 週末の午後(14:00～16:00)

検索機能を使う時は3と4と勝手に想像しているのですが
（管理人さんが検索クエリのデータを持ってらっしゃるのかなとーも）

例えば#26の場合、自身への言及を検索するのが目的で
私の場合、新着履歴のページブックマーク代わりに使う事が多いです。

他の方はどういうユーザー像を想定されていますか？

**Comment by mikageymir** [comment]
> 機能としてほしいのは
>・検索履歴 ・検索クエリをブラウザのブックマークに登録したい。 　(理想はPixivのお気に入りタグ)
> 　理由：タグでウォッチしたいため

検索履歴は良さそうですね。

pixivの方を見てきましたが、クエリの履歴とお気に入り登録は動きがちょっと違うようですね。

・検索すると自動で履歴に記録される。（全体のクリアは可能）
・キーワード入力での検索、履歴からの検索は、タイトルや本文等も検索対象（たぶん）
・お気に入り登録ボタンを押すと、そのキーワードのタグが登録される。
・登録されたタグをクリックすると、キーワードではなくタグでの検索が実行される。
・「#猫耳」などで検索してもタグでは検索できず、タグでの検索はお気に入り登録でやる必要がある。

そのまま真似するのはちょっとわかりにくそうですね(^^;

pixivと違い、ピクターズには様々なフィルタが可能になっているので、フィルタ条件も含めて履歴が残る、
お気に入り登録もできるのが良さそうでしょうか。

**Comment by mikageymir** [comment]
> ちゃぶ台をひっくり返すようで申し訳ないのですが、検索やランキングについて個人的に気になっている点です。 別IssueかDiscussionsのほうが良いでしょうか。

とりあえずこちらで意見を集めて、別々に作ったほうが良いような内容でしたら
後で別Issue立ち上げるで良いかと思います。

> 1. 検索画面のUIについて
>    検索機能やUI全体として、TwitterやPinterestの画面が、個人的に慣れていて使いやすく好みなのですが、
>    他の方はどう感じているのか気になりました。
>    （このまま、どんどん機能追加していくと、検索項目が多く管理人さんが保守しずらくなる点も懸念しています。）

Twitterだと、とりあえず結果が出て、右側にフィルターが出ますね。
こういうUIもいいかもしれませんね。。。

一応私の案では、結果がすぐにみれるようにフィルタは初期で折りたたむものを想定していました。
（ピクターズさんのデザインだと、基本横幅目一杯つかって作品の一覧性高めていると思いますので、そこはそのまま）

> 2. 検索機能を使われる方のペルソナ(ユーザー像)が気になりました。
>（略）
> 例えば#26の場合、自身への言及を検索するのが目的で 私の場合、新着履歴のページブックマーク代わり(ホームはランキングが初期値でブックマークができないので)に使う事が多いです。

自身の作品に対しては、通知履歴から確認できると思います。
一方で現状の検索はキャプションが検索対象に入ってないので、作品投稿時に言及されてもヒットしないと思います。
また、コメントも検索対象ではないので、検索できてなさそうな気もするのですが、どうされてるのでしょうか。。。

この辺わたしも仕様把握しきれてなくて間違った理解しているかもです💦
入力ワードに対して、タイトルとプロンプトの部分一致＋タグの完全一致、の認識です。

> 他の方はどういうユーザー像を想定されていますか？

ユーザというか、私の想定では以下のような検索をする見込みでした。
・タグによる検索（作品ページからのリンク先を併用）
　そのタグの作品を閲覧する目的（観賞用）
　1回目はいいね順での閲覧も良さそう。条件保存するなら新しい順にすれば定期的閲覧用に。
・ユーザ名による検索。
　例えばディスコ等で名前を見て、この人の作品みてみよう、と思ったとき
・プロンプトで検索。
　自分で作っている特定のキーワードで検索し、他の人のプロンプトを見て作品作りの参考に。
・モデルで検索。
　自分で使ってるモデルの他の作品を見たり、使おうか検討しているモデルの作品例を探す。

といったあたりかなぁと思ってます。

**Comment by nakatsuka-k** [comment]
mikageさん、haruharuさん、ありがとうございます。
ご記載いた抱いたようにTwitterなどの既存サービスのシンプルさに寄せた方がよさそうです。
検索機能の対象のユーザについてはご記載頂いた通りで認識合っております。
- 平日の夕方(18:00～19:00)
- 週末の午後(14:00～16:00)

まず、下記機能を搭載する方向で進めたいです。

＞・検索履歴
＞・検索クエリをブラウザのブックマークに登録したい。
＞　(理想はPixivのお気に入りタグ)
＞　理由：タグでウォッチしたいため

mikageさんがご記載頂いた下記の利用ケースも想定通りです。

＞・タグによる検索（作品ページからのリンク先を併用）
＞　そのタグの作品を閲覧する目的（観賞用）
＞　1回目はいいね順での閲覧も良さそう。条件保存するなら新しい順にすれば定期的閲覧用に。
＞・ユーザ名による検索。
＞　例えばディスコ等で名前を見て、この人の作品みてみよう、と思ったとき
＞・プロンプトで検索。
＞　自分で作っている特定のキーワードで検索し、他の人のプロンプトを見て作品作りの参考に。
＞・モデルで検索。
＞　自分で使ってるモデルの他の作品を見たり、使おうか検討しているモデルの作品例を探す。

**Comment by mikageymir** [comment]
検索の新しいUI案です。

意図：
・他サイトをみても、入力して検索したときに、検索キーワードを入れる欄が他の場所に切り替わるケースはありません。
　現状ですと下の入力欄に切り替わり、サイトトップに入力し直しても意図した動作にならないため、入力は常に
　サイト上部から行うUIに変更しました。
・検索結果を最初の表示でなるべく多く視界に入るようにするため、詳細設定はダイアログに変更します。
　ダイアログ内で設定し、ダイアログを閉じると新しい設定で再検索される形です。

ダミーなので検索結果はないですが、画面イメージはこのような形。
<img width="796" alt="image" src="https://user-images.githubusercontent.com/22807407/236615405-71eeae2c-aa20-4ae9-982f-acfff714bed4.png">

検索設定ボタンで、以下のようなダイアログを表示します。
今と大きな違いとして、デフォルトで投稿者名・キャプションも検索対象になります。
（ダイアログで検索対象から除外可能です）

<img width="798" alt="image" src="https://user-images.githubusercontent.com/22807407/236615431-92fb53c9-2b01-4d3d-937b-8df16034405c.png">

その他、画面上部の検索欄クリックで、
・検索履歴を表示する（Twtter/pixivのようなイメージ）
・タグ一覧を読み込み、入力によりタグが補完されるようにする
を行おうと思います。


また、検索キーワード入力は以下のようにしようと思います。

AND検索：スペース区切りでAND検索
NOT検索：-キーワード、形式で指定。-tag:タグ、のように条件指定も可。
タグ検索：tag:タグ名
タイトル検索：title:タイトル
キャプション検索：explanation:キャプション
プロンプト検索：prompt:プロンプト
投稿者検索：owner:投稿者名
フレーズ検索："pink hair" で1単語として検索。プロンプト限定なら prompt:"pink hair" のように指定。

キーワードで検索しつつ、特定のタグやプロンプトを除外するような使い方もできるようになります。

**Comment by haruharu-1105** [comment]
新しい画面レイアウトのイメージ作成ありがとうございます。
よりイメージがつくようになり助かりました。

検索設定画面は、検索後に検索件数を変更する用途があるため、
一つ前の検索条件を記憶するイメージです認識相違ないでしょうか。

大きな変更点として、検索設定画面で検索ボタンで再検索を行う点と思いますが（勘違いしていたら申し訳ないです）
ダイアログの変更をリアルタイムに結果に反映するのが好みです。

以下からは提案です、他の作業の兼ね合い等もあるので、全部反映して頂かなくても問題ありません。
上から順に追加して欲しい内容です。

【検索設定画面】
・スマフォユーザー向けに検索ボタンは固定化して欲しいです。
　検索項目が多いため
・画面に履歴ボタン（時計アイコン）を追加し、過去の履歴を照会・適用可能にして欲しいです。
　検索設定画面で、検索履歴を適用し検索するのを想定しています。
・検索ボタンの行の左側にスペースを開けて検索の「フィルター解除」ボタンを追加して欲しいです。
　検索項目の初期化を想定しています。
・画面に「閉じる」を追加して欲しいです。
・タイトルを検索設定から、操作内容を表す「絞り込み」に変更して欲しいです。
・項目「ソート順」を「並び替え」または「並び順」に変更して欲しいです。
　システム全体で共通の単語があれば、そちらでOKです。
　理由はソートはIT用語なので、より一般的な単語に変更して欲しいです。

**Comment by mikageymir** [comment]
ご意見ありがとうございます！

> 検索設定画面は、検索後に検索件数を変更する用途があるため、 一つ前の検索条件を記憶するイメージです認識相違ないでしょうか。

以下のようなイメージです。

・画面上部にキーワードを入れて検索すると、デフォルトの設定で検索結果画面が表示される。
　その結果一覧の上に「検索設定」のボタンがある形です。
・検索結果を表示後に、検索設定を押すと、検索結果はグレーアウトして手前にダイアログが表示され、
　その中で設定を変更できます。変更後ダイアログを閉じると、新しい条件での検索結果が表示されます。

> 大きな変更点として、検索設定画面で検索ボタンで再検索を行う点と思いますが（勘違いしていたら申し訳ないです） ダイアログの変更をリアルタイムに結果に反映するのが好みです。

上記の通り、ダイアログは検索結果の上に表示され、背景はグレーアウトする形を想定しています。
なので、条件を変えてダイアログを閉じるまでは反映させない形を想定しています。

現状ですと、条件を変えると都度リアルタイムで更新されるのですが、今のサーバの仕組み上、
作品数に比例して検索処理が重くなることは避けられそうにないため、検索処理の頻度を
下げる意図もあって、ダイアログ表示にしようかと考えておりました。

> 【検索設定画面】
>・スマフォユーザー向けに検索ボタンは固定化して欲しいです。 　検索項目が多いため

固定化というのは、ダイアログ全体が画面内に入らない場合に、条件部分がスクロール領域になり、
検索ボタンがダイアログの下に常にでている、というイメージであってますでしょうか。
そのようにしようと思います。

>・画面に履歴ボタン（時計アイコン）を追加し、過去の履歴を照会・適用可能にして欲しいです。
>検索設定画面で、検索履歴を適用し検索するのを想定しています。

はい、こちらは対応予定です。
履歴＋pixivのようにオススメ表示までできればと思ってます。
（とはいえまずは検索自体のみになりそうです）

UIとしては、Twitter/pixivのように、検索キーワード欄をクリックすると、その下に
履歴が表示される形が馴染みがあって良いかなと考えています。

> ・検索ボタンの行の左側にスペースを開けて検索の「フィルター解除」ボタンを追加して欲しいです。
> 　検索項目の初期化を想定しています。 

検索詳細設定はダイアログであるため、サイトの上部の検索キーワードにキーワードを入れると、
デフォルトの設定で検索できる形を想定していました。

例えばサイト上部に「メイド」でキーワード検索すると、デフォルトの設定で検索結果が表示されます。
その状態で、検索条件をクリックして、R18・R18Gを対象に加えて閉じると、R18作品含めた検索結果になります。

そこまで進めた状態で、サイト上部に別のキーワードを入れた場合は、先程の条件はリセットされ、
標準の条件で検索される動作を想定しておりました。
（こちらはある程度条件を保存したいというご要望はあるかもしれませんね。。。）

>・画面に「閉じる」を追加して欲しいです。

こちらダイアログの右上に、✕ボタンを追加するイメージでしょうか？

>・タイトルを検索設定から、操作内容を表す「絞り込み」に変更して欲しいです。

ありがとうございます。たしかにそちらのほうがわかりやすそうですね。変更しようと思います。

> ・項目「ソート順」を「並び替え」または「並び順」に変更して欲しいです。
> 　システム全体で共通の単語があれば、そちらでOKです。
> 　理由はソートはIT用語なので、より一般的な単語に変更して欲しいです。

たしかにそうですね。変更しようと思います。

**Comment by mikageymir** [comment]
検索履歴はまだですが、検索機能自体の実装は一旦完了しました。
こちらのチケットはクローズして、履歴については別チケットにいたします。
