### ISSUE TITLE
サイト障害中のランキング・通知等の復旧

### ISSUE THREAD

**Issue by mikageymir** [aipictors/feedback#28]
サイト障害中のバッチ処理が動かず、ランキング等の通知が欠落している。

・4/21のデイリーランキングの通知
・4/21の実績とトロフィー
・4/21分のデイリー入賞の表示

ディスコードログ：
https://discord.com/channels/1069968879272595476/1071457705627238460/1099246390070222968

**Comment by nakatsuka-k** [comment]
大変申し訳ございません。
こちらサーバ停止などの対策などの作業が立て込み対応が遅れてしまいました。
現時点から対応した場合、別の不具合を引き起こしてしまう可能性があるため
大変申し訳無いのですが一旦Closeとさせていただき、一括で整合性取れる機能の搭載ができれば
対応いたします。
