### ISSUE TITLE
AI小説を投稿できる機能

### ISSUE THREAD

**Issue by mikageymir** [aipictors/feedback#3]
管理人さんコメント：
>AI小説専門のプラットフォームとのことで、AIピクターズ内に併設でも問題無いでしょうか。
>AIピクターズ内にInstagramのように様々なコンテンツを分けて閲覧できる機能があればよさそうかとは考えております。
>また、ユーザのフォローしている方のイラスト、小説をカテゴリ分けしてキャッチアップできるのでクリエイティブな活動を追いやすい気もしております。 

ディスコードログ：
https://discordapp.com/channels/1069968879272595476/1069969218923139202/1097230197658505277

**Comment by nakatsuka-k** [comment]
小説機能を搭載させていただいたため、Closeとさせていただきます。
