### ISSUE TITLE
ミュート機能の強化（タグのミュート）

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/feedback#38]
- 事象
現状のミュートはユーザー単位です。
ミュート機能を投稿作品のタグで行えるようにして欲しいです。

-メリット
Pixivとの区別化
(Pixivはプレミアムユーザー以外はタグのミュート機能が１個しか行えないため）

- デメリット
・投稿作品のタグ情報を検索する必要が発生するので、検索時のパフォーマンスに影響
・機能追加しても、タグを追加せずに投稿するユーザーが増える可能性があります。

**Comment by nakatsuka-k** [comment]
起票頂きありがとうございます。
ご記載頂いたようにPixivにもある機能でしたら追加させて頂きます。
ご懸念頂いた点についてもご記載の通りかとは思います。
パフォーマンスについてはミュートタグを追加していないユーザには影響はありませんが
追加しているユーザの場合はやや速度が落ちる可能性はありそうです。

**Comment by mikageymir** [comment]
ミュートタグ機能リリースされました！
https://twitter.com/AIPICTORS/status/1658814629378924544

検索部分は手伝わせていただきましたが、ほぼパフォーマンス影響なくご利用いただける形にできたと思います。

**Comment by nakatsuka-k** [comment]
素晴らしいです。ありがとうございます。

**Comment by haruharu-1105** [comment]
返信が遅れて申し訳ありませんでした。
ミュートタグ機能の対応ありがとうございました。
