### ISSUE TITLE
フィッシング対策として自動リンクの対処

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/feedback#39]
- 事象
投稿作品のキャプション欄やコメント欄にて、自動リンクが有効です。
そのため、悪意の持ったユーザーが投稿作品にリンクをつけて投稿すると、誤クリックが発生します。

- 対応案
案1, クリック時にポップアップし、信頼するドメインを記憶する(Discord)
案2, 自動リンク機能を無効化(Skeb)
案3, クッションページを挟み、ワンクリックでの遷移を防止(Pixiv)
案4, リンク先のホワイトリスト化
　　→案1～案3と比較すると、運用コストで現実的ではないかなと思いましたが、一応候補に上げます。
案5, そのまま。(TwitterやFanbox)

- デメリット
ユーザービリティの低下

**Comment by nakatsuka-k** [comment]
起票頂きありがとうございます。
ご記載の通り外部リンクへの遷移時にワンクッション挟むように致します。
ご記載の通りTwitterなどだと不要なはずなのでホワイトリストも導入させて頂きます。
