### ISSUE TITLE
R18ボタンやその下のボタンが特定のウインドーサイズのときに崩れます。

### ISSUE THREAD

**Issue by nauzome** [aipictors/feedback#42]
R18ボタンやその下のボタンが特定のウインドーサイズのときに崩れます。
軽く確認したところ .pc-side-menu が邪魔しているぽいです。
多分詳細に確認していませんが .pc-side-menu を適切な場所に移動する事で改善できると思います。
当方はwordpressのテーマや作成などを知らずお役には立てませんがご報告まで...。
![image](https://github.com/nakatsuka-k/AIPictors/assets/84845207/2bad4115-4e2f-4dad-bedf-fd873b301eb4)
https://www.aipictors.com/

**Comment by nakatsuka-k** [comment]
[nauzome](https://github.com/nauzome)さん、原因調査まで頂きありがとうございます。
大変助かります。
一旦修正の上、手元の環境では改善されているように見えておりますが
再発、もしくは別の問題が発生していそうでしたらお申しつけ頂けますと幸いです。
![image](https://github.com/aipictors/feedback/assets/124619691/27d28aac-37b9-436d-8da2-94df0544add9)

**Comment by nauzome** [comment]
ありがとうございます、解決しました。

**Comment by nakatsuka-k** [comment]
ご確認頂きありがとうございます。
