### ISSUE TITLE
検索履歴に対応する

### ISSUE THREAD

**Issue by mikageymir** [aipictors/feedback#47]
検索ボックスクリック時に、その下に検索履歴を表示する。
（TwitterやPixivのように）

**Comment by mikageymir** [comment]
管理人さん、nzさんにデザイン等協力いただきまして、実装完了です。
使い方等はWikiに記載しました。
https://w.atwiki.jp/aipictors/pages/17.html

**Comment by nauzome** [comment]
素晴らしいニュースです。
そしてお疲れ様です。

**Comment by nakatsuka-k** [comment]
ご対応ありがとうございます！
