### ISSUE TITLE
小説の投稿ガイドラインの作成

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/feedback#48]
小説機能の投稿ガイドラインを作成して欲しいです。

### ◯ガイドラインに記載して欲しい事項

**- 禁止して欲しい事項**
1. 歌詞についての扱い（JASRAC）
　[小説家になろう　歌詞転載に関して](https://syosetu.com/site/song/)
　JASRAC内のFAQ[著作権と利用手続き　編曲・替歌をするときの注意点](https://www.jasrac.or.jp/copyright/use/index.html#anc01)
1. 選挙運動
　[現行の選挙運動の規制](https://www.soumu.go.jp/senkyo/senkyo_s/naruhodo/naruhodo10_1.html)
　→一律NGで提案致します。理由は、私としてはピクターズで取り扱う内容ではないと思います。

**- 推奨して欲しい事項**

1. 非推奨コメントの記載の推奨
> https://kakuyomu.jp/legal/guideline
**表現についてご留意いただきたいこと**
(中略)
 「未成年の飲酒・喫煙」など、法律で禁止されている行為について、物語の表現上やむをえず描写する場合は、そういった描写のある作品の紹介文の末尾に『この物語は、法律・法令に反する行為を容認・推奨するものではありません』など、行為の非推奨コメントを記載してください。

**- 決定して欲しい事項**
- 二次創作
[小説家になろう　二次創作の投稿に関して](https://syosetu.com/site/nizi/)
- ナマモノの扱い
上記二次創作に関連しますが、芸能人・有名人・Vtuber
[【初心者向け】ナマモノ(nmmn)の意味と創作のルールまとめ](https://dounats.com/column/nmmn-mean-rule/)
- 同人活動
宣伝リンク等もあると思いますので上げておきます。

**- 参考リンク**
・他の小説投稿サイトの規約やガイドラインです。
[ハーメルン 利用規約](https://syosetu.org/rule.html)　改定履歴が参考になるかもです。
[カクヨム小説投稿ガイドライン](https://kakuyomu.jp/legal/guideline)

ディスコードログ：
https://discord.com/channels/1069968879272595476/1069969218923139202/1109835890286678026

**Comment by nakatsuka-k** [comment]
ありがとうございます。
下記追記しております。
https://www.aipictors.com/terms/

＞歌詞についての扱い（JASRAC）
歌詞掲載について　以降記載

＞選挙運動
・過度な宗教、政治活動を表現しているもの

＞非推奨コメントの記載の推奨
・小説について、「未成年の飲酒・喫煙」など、法律で禁止されている行為について、物語の表現上やむをえず描写する場合は、そういった描写のある作品の紹介文の末尾に『この物語は、法律・法令に反する行為を容認・推奨するものではありません』など、行為の非推奨コメントを記載してください。

＞二次創作
小説について、原作の権利者様が二次創作の許可に関する意見表明を第三者が閲覧可能な状態で公開しているものについては二次創作したものをご投稿いただけます。

＞ナマモノの扱い
・ 芸能人などの実在する人物が登場する作品の投稿

＞同人活動
特に迷惑行為にならない場合は禁止なし

**Comment by nakatsuka-k** [comment]
一旦こちら問題なさそうでしたらFIxさせていただきます。
また何かございましたらお申し付けいただけますと幸いです。

**Comment by haruharu-1105** [comment]
規約確認しました。
問題ないです、追記ありがとうございました。

**Comment by nakatsuka-k** [comment]
haruharuさん、お疲れ様です。
お忙しいところご確認いただき、ありがとうございました。
